//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapisiparisproje.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class siparisapiEntities : DbContext
    {
        public siparisapiEntities()
            : base("name=siparisapiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblmusteriler> tblmusterilers { get; set; }
        public virtual DbSet<tblsiparisdetay> tblsiparisdetays { get; set; }
        public virtual DbSet<tblsiparisler> tblsiparislers { get; set; }
        public virtual DbSet<tblkullanici> tblkullanicis { get; set; }
    }
}
