//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapisiparisproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsiparisler
    {
        public int siparisid { get; set; }
        public string siparisadi { get; set; }
        public string siparistarihi { get; set; }
    }
}
